# 6. Create an AI-Powered Sales Report Analyzer with LlamaIndex

In [2]:
%pip install llama-index llama-index-llms-openai-like
import os
import pandas as pd
from llama_index.core import Document, VectorStoreIndex, Settings
from llama_index.core.embeddings import MockEmbedding
from llama_index.llms.openai_like import OpenAILike
# Groq API key
os.environ["GROQ_API_KEY"] = "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"

# Sales report data
df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar", "Apr", "May"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile"],
    "Region": ["South", "North", "East", "West", "South"],
    "Revenue": [50000, 40000, 25000, 60000, 55000],
    "Profit": [10000, 8000, 4000, 12000, 11000]
})
display(df)
# Convert table into document
data_text = df.to_string(index=False)


# Use Groq with OpenAI-compatible endpoint
Settings.llm = OpenAILike(
    model="openai/gpt-oss-20b",
    api_key=os.environ["GROQ_API_KEY"],
    api_base="https://api.groq.com/openai/v1",
    is_chat_model=True,
    is_function_calling_model=False
)
# Simple embedding for classroom demo
Settings.embed_model = MockEmbedding(embed_dim=384)

document = Document(
    text=f" Sales Report:{data_text}"
)
# Create LlamaIndex index
index = VectorStoreIndex.from_documents([document])
# Create query engine
query_engine = index.as_query_engine()
# Ask question
response = query_engine.query(
    "Which product generated the highest total revenue? Show calculation."
)
print(response)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: llama-index in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (0.14.24)
Requirement already satisfied: llama-index-llms-openai-like in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (0.7.2)
Requirement already satisfied: llama-index-core<0.15.0,>=0.14.24 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index) (0.14.24)
Requirement already satisfied: llama-index-embeddings-openai<0.7,>=0.6.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index) (0.6.0)
Requirement already satisfied: llama-index-llms-openai<0.8,>=0.7.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index) (0.7.10)
Requirement already satisfied: nltk>=3.9.3 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index) (3.10.3)
Requirement already satisfied: aiohttp<4,>=3.8.6 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (3.14.3)
Requirement already satisfied: aiosqlite in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.5.0)
Requirement already satisfied: dataclasses-json in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (1.3.1)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2026.7.0)
Requirement already satisfied: httpx in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (0.28.1)
Requirement already satisfied: llama-index-workflows<3,>=2.14.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.23.3)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (3.6.1)
Requirement already satisfied: numpy in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.5.2)
Requirement already satisfied: pillow>=9.0.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (12.3.0)
Requirement already satisfied: platformdirs in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (4.5.0)
Requirement already satisfied: pydantic>=2.8.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.13.4)
Requirement already satisfied: pyyaml>=6.0.1 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.32.5)
Requirement already satisfied: setuptools>=80.9.0 in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (80.9.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.0.43)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (9.1.2)
Requirement already satisfied: tiktoken>=0.7.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (0.14.0)
Requirement already satisfied: tinytag>=2.2.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.3.0)
Requirement already satisfied: tqdm<5,>=4.66.1 in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (4.67.1)
Requirement already satisfied: typing-extensions>=4.5.0 in C:\ProgramData\anaconda3\Lib\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (4.15.0)
Requirement already satisfied: typing-inspect>=0.8.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (0.9.0)
Requirement already satisfied: wrapt in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-core<0.15.0,>=0.14.24->llama-index) (2.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.24->llama-index) (1.24.5)
Requirement already satisfied: griffe in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.2.0)
Requirement already satisfied: jinja2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (3.1.6)
Requirement already satisfied: openai>=1.1.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (2.54.0)
Requirement already satisfied: llama-index-instrumentation>=0.4.3 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from llama-index-workflows<3,>=2.14.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (0.5.0)
Requirement already satisfied: anyio<5,>=3.5.0 in C:\ProgramData\anaconda3\Lib\site-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in C:\ProgramData\anaconda3\Lib\site-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (0.16.0)
Requirement already satisfied: sniffio in C:\ProgramData\anaconda3\Lib\site-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (1.3.0)
Requirement already satisfied: idna>=2.8 in C:\ProgramData\anaconda3\Lib\site-packages (from anyio<5,>=3.5.0->openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama-index) (3.11)
Requirement already satisfied: certifi in C:\ProgramData\anaconda3\Lib\site-packages (from httpx->llama-index-core<0.15.0,>=0.14.24->llama-index) (2025.11.12)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx->llama-index-core<0.15.0,>=0.14.24->llama-index) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx->llama-index-core<0.15.0,>=0.14.24->llama-index) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.4 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (0.4.2)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from tqdm<5,>=4.66.1->llama-index-core<0.15.0,>=0.14.24->llama-index) (0.4.6)
Requirement already satisfied: defusedxml in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from nltk>=3.9.3->llama-index) (0.7.1)
Requirement already satisfied: click in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from nltk>=3.9.3->llama-index) (8.4.2)
Requirement already satisfied: joblib in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from nltk>=3.9.3->llama-index) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from nltk>=3.9.3->llama-index) (2026.7.19)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.5.0)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.24->llama-index) (3.2.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in C:\ProgramData\anaconda3\Lib\site-packages (from typing-inspect>=0.8.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (1.0.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from dataclasses-json->llama-index-core<0.15.0,>=0.14.24->llama-index) (3.26.2)
Requirement already satisfied: packaging>=17.0 in C:\ProgramData\anaconda3\Lib\site-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.15.0,>=0.14.24->llama-index) (25.0)
Requirement already satisfied: griffecli==2.2.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.2.0)
Requirement already satisfied: griffelib==2.2.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (2.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from jinja2->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.24->llama-index) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

  Month Product Region  Revenue  Profit
0   Jan  Laptop  South    50000   10000
1   Feb  Mobile  North    40000    8000
2   Mar  Tablet   East    25000    4000
3   Apr  Laptop   West    60000   12000
4   May  Mobile  South    55000   11000

**Laptop** generated the highest total revenue.

Calculation:
- January Laptop: $50,000
- April Laptop: $60,000

Total Laptop revenue = $50,000 + $60,000 = **$110,000**.

# 7 Create a Market Research Agent with RAG & Cohere

In [5]:
!pip install -U cohere numpy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cohere in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (7.1.0)
Requirement already satisfied: numpy in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (2.5.2)
Requirement already satisfied: pandas in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (3.0.5)
Requirement already satisfied: fastavro<2.0.0,>=1.9.4 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (1.12.2)
Requirement already satisfied: httpx>=0.25.0 in C:\ProgramData\anaconda3\Lib\site-packages (from cohere) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (2.13.4)
Requirement already satisfied: pydantic-core<3.0.0,>=2.18.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (2.46.4)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from cohere) (2.32.5)
Requirement already satisfied: tokenizers<1,>=0.15 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (0.22.2)
Requirement already satisfied: types-requests<3.0.0,>=2.0.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (2.33.0.20260712)
Requirement already satisfied: typing_extensions>=4.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from cohere) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (2025.11.12)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from tokenizers<1,>=0.15->cohere) (1.28.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (3.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (1.6.0)
Requirement already satisfied: packaging>=20.9 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (25.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (4.67.1)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (0.4.6)
Requirement already satisfied: anyio in C:\ProgramData\anaconda3\Lib\site-packages (from httpx>=0.25.0->cohere) (4.10.0)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx>=0.25.0->cohere) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx>=0.25.0->cohere) (0.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from pandas) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=1.9.2->cohere) (0.6.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=1.9.2->cohere) (0.4.2)
Requirement already satisfied: six>=1.5 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in C:\ProgramData\anaconda3\Lib\site-packages (from anyio->httpx>=0.25.0->cohere) (1.3.0)

In [9]:
# Install required package
%pip install -U cohere

# API Keys
import os
os.environ["COHERE_API_KEY"] = "y3roeFf01TazGMVWV2Aj8MMHmFOT2j6qq4K98EOo"

# Import Cohere
import cohere

# Create Cohere client
co = cohere.ClientV2()

# Documents for RAG
documents = [
    "Indian EV demand is led by two-wheelers and urban mobility.",
    "High battery cost and few charging stations slow EV adoption.",
    "Tata, Ola, Ather and Mahindra are major EV competitors.",
]

# User query
query = "Give a short market report on electric vehicles in India."

# Rerank documents
ranked = co.rerank(
    model="rerank-v3.5",
    query=query,
    documents=documents,
    top_n=2
)

# Select the top-ranked documents
context = "\n".join(
    documents[item.index]
    for item in ranked.results
)

# Generate final report
response = co.chat(
    model="command-a-03-2025",
    messages=[
        {
            "role": "user",
            "content": f"{query}\nUse only:\n{context}"
        }
    ],
)

# Print result
print(response.message.content[0].text)

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cohere in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (7.1.0)
Requirement already satisfied: fastavro<2.0.0,>=1.9.4 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (1.12.2)
Requirement already satisfied: httpx>=0.25.0 in C:\ProgramData\anaconda3\Lib\site-packages (from cohere) (0.28.1)
Requirement already satisfied: pydantic>=1.9.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (2.13.4)
Requirement already satisfied: pydantic-core<3.0.0,>=2.18.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (2.46.4)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from cohere) (2.32.5)
Requirement already satisfied: tokenizers<1,>=0.15 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (0.22.2)
Requirement already satisfied: types-requests<3.0.0,>=2.0.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from cohere) (2.33.0.20260712)
Requirement already satisfied: typing_extensions>=4.0.0 in C:\ProgramData\anaconda3\Lib\site-packages (from cohere) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\ProgramData\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.0.0->cohere) (2025.11.12)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from tokenizers<1,>=0.15->cohere) (1.28.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (3.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (1.6.0)
Requirement already satisfied: packaging>=20.9 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (25.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in C:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (4.67.1)
Requirement already satisfied: colorama in C:\ProgramData\anaconda3\Lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=0.16.4->tokenizers<1,>=0.15->cohere) (0.4.6)
Requirement already satisfied: anyio in C:\ProgramData\anaconda3\Lib\site-packages (from httpx>=0.25.0->cohere) (4.10.0)
Requirement already satisfied: httpcore==1.* in C:\ProgramData\anaconda3\Lib\site-packages (from httpx>=0.25.0->cohere) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\ProgramData\anaconda3\Lib\site-packages (from httpcore==1.*->httpx>=0.25.0->cohere) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=1.9.2->cohere) (0.6.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\ProgramData\anaconda3\Lib\site-packages (from pydantic>=1.9.2->cohere) (0.4.2)
Requirement already satisfied: sniffio>=1.1 in C:\Users\comps\AppData\Roaming\Python\Python313\site-packages (from anyio->httpx>=0.25.0->cohere) (1.3.1)
Note: you may need to restart the kernel to use updated packages.
**Indian Electric Vehicle Market Report**

India’s electric vehicle (EV) market is experiencing steady growth, primarily driven by **two-wheelers and urban mobility solutions**. Two-wheelers dominate demand due to affordability, lower operational costs, and increasing consumer awareness of sustainability. Urban mobility, including electric rickshaws and ride-sharing services, is also gaining traction as cities push for cleaner transportation options.

Key players in the Indian EV space include **Tata Motors**, **Ola Electric**, **Ather Energy**, and **Mahindra & Mahindra**. Tata Motors leads the four-wheeler segment with models like the Nexon EV, while Ola Electric dominates the two-wheeler market with its popular electric scooters. Ather Energy has carved a niche in premium electric scooters, and Mahindra continues to expand its EV portfolio across segments.

With government incentives, improving charging infrastructure, and rising fuel prices, India’s EV market is poised for further growth, led by these major competitors and the increasing demand for sustainable urban mobility.

# 8

In [8]:
%pip install -U phidata
import os
import pandas as pd

from phi.agent import Agent
from phi.model.groq import Groq

# Use your NEW Groq API key
os.environ["GROQ_API_KEY"] = "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"

# Sample sales data
df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar", "Apr", "May"],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile"],
    "Region": ["South", "North", "East", "West", "South"],
    "Revenue": [50000, 40000, 25000, 60000, 55000],
    "Profit": [10000, 8000, 4000, 12000, 11000]
})

display(df)

# Convert dataframe to text
data_text = df.to_string(index=False)

# Create Phidata agent
data_agent = Agent(
    name="Data Analysis Agent",
    model=Groq(id="openai/gpt-oss-120b"),
    instructions=[
        "You are a data analysis assistant.",
        "Analyze the given sales data carefully.",
        "Show calculations clearly.",
        "Give short business insights."
    ],
    markdown=True
)

# Question
question = "Which product has the highest total revenue? Show calculation."

# Run agent
response = data_agent.run(
    f"""
Here is the sales data:

{data_text}

Question:
{question}
"""
)

print(response.content)

  Month Product Region  Revenue  Profit
0   Jan  Laptop  South    50000   10000
1   Feb  Mobile  North    40000    8000
2   Mar  Tablet   East    25000    4000
3   Apr  Laptop   West    60000   12000
4   May  Mobile  South    55000   11000

**Total Revenue by Product**

| Product | Revenue (Jan) | Revenue (Apr) | Revenue (Feb) | Revenue (May) | Revenue (Mar) | **Total Revenue** |
|---------|--------------|--------------|--------------|--------------|--------------|-------------------|
| Laptop  | 50,000 | 60,000 | – | – | – | **110,000** |
| Mobile  | – | – | 40,000 | 55,000 | – | **95,000** |
| Tablet  | – | – | – | – | 25,000 | **25,000** |

**Calculation**

- **Laptop:** 50,000 (Jan) + 60,000 (Apr) = **110,000**
- **Mobile:** 40,000 (Feb) + 55,000 (May) = **95,000**
- **Tablet:** 25,000 (Mar) = **25,000**

**Answer**

The **Laptop** product has the highest total revenue, amounting to **$110,000**.

**Brief Insight**

- Laptops generate the most revenue despite being sold in only two months, indicating a strong market demand or higher price point.
- Mobile devices are close behind; focusing on cross‑selling or bundling could capture additional share.
- Tablet sales are comparatively low, suggesting an opportunity to either boost marketing or re‑evaluate the product offering in that segment.

In [8]:
import pandas as pd
import os
from phi.agent import Agent
from phi.model.groq import Groq

os.environ["GROQ_API_KEY"]="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"

df = pd.DataFrame({
    "Month":["January","February","March","April","May"],
    "Product":["Laptop","Mobile","Tablet","Laptop","Mobile"],
    "Region":["North","South","East","West","South"],
    "Revenue":[50000,40000,25000,60000,55000],
    "Profit":[8000,10000,6000,12000,15000]
})

print(df)

data_text = df.to_string(index=False)

agent = Agent(
    name = "Data Analysis Agent",
    model = Groq(id="openai/gpt-oss-20b"),
    instructions=[
        "You are a Data Analysis Agent",
        "you have to carefully analyze the data provided",
        "You have to interpret the data correctly and provide reasoning for the decisions you make",
        "Make proper calculations"
    ]
)

question = "which product has the highest total revenu and which region has the highest profit"

response = agent.run(f" Question = {question} Data : {data_text}")

print(response.content)

      Month Product Region  Revenue  Profit
0   January  Laptop  North    50000    8000
1  February  Mobile  South    40000   10000
2     March  Tablet   East    25000    6000
3     April  Laptop   West    60000   12000
4       May  Mobile  South    55000   15000
**Step‑by‑step calculation**

| Month   | Product | Region | Revenue | Profit |
|---------|---------|--------|---------|--------|
| January | Laptop  | North  | 50,000  | 8,000  |
| February| Mobile  | South  | 40,000  | 10,000 |
| March   | Tablet  | East   | 25,000  | 6,000  |
| April   | Laptop  | West   | 60,000  | 12,000 |
| May     | Mobile  | South  | 55,000  | 15,000 |

---

### 1. Highest total revenue by product

Add the revenue values for each product:

| Product | Sum of Revenue |
|---------|----------------|
| Laptop  | 50,000 + 60,000 = **110,000** |
| Mobile  | 40,000 + 55,000 = 95,000 |
| Tablet  | 25,000 |

**Result:** The product with the highest total revenue is **Laptop** (110,000).

---

### 2. Highest profit by region

Add the profit values for each region:

| Region | Sum of Profit |
|--------|---------------|
| North  | 8,000 |
| South  | 10,000 + 15,000 = **25,000** |
| East   | 6,000 |
| West   | 12,000 |

**Result:** The region with the highest total profit is **South** (25,000).

---

**Answer**

- **Product with the highest total revenue:** **Laptop**
- **Region with the highest total profit:** **South**